name: 'CodeQL SARIF Report'
description: 'Generate and upload SARIF HTML reports from CodeQL analysis'
author: 'felickz'
branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  sarif-input:
    description: 'Path to the SARIF output directory. Defaults to CODEQL_ACTION_SARIF_RESULTS_OUTPUT_DIR environment variable set by codeql-action.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install sarif-tools
      shell: bash
      run: |
        pip install sarif-tools==2.0.0

    - name: Set environment variables
      shell: bash
      run: |
        REPO_NAME="$(echo '${{ github.repository }}' | tr '/' '-')"
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

    - name: Generate SARIF HTML reports
      shell: bash
      env:
        INPUT_SARIF_DIR: ${{ inputs.sarif-input }}
      run: |
        SARIF_DIR="$INPUT_SARIF_DIR"
        if [ -z "$SARIF_DIR" ]; then
          SARIF_DIR="${CODEQL_ACTION_SARIF_RESULTS_OUTPUT_DIR}"
        fi

        if [ -z "$SARIF_DIR" ]; then
          echo "Error: No SARIF directory specified and CODEQL_ACTION_SARIF_RESULTS_OUTPUT_DIR is not set"
          exit 1
        fi

        if [ ! -d "$SARIF_DIR" ]; then
          echo "Error: SARIF directory not found: $SARIF_DIR"
          exit 1
        fi

        FOUND_FILES=0
        while IFS= read -r -d '' SARIF_FILE; do
          BASENAME=$(basename "$SARIF_FILE" .sarif)
          echo "Generating HTML report for $SARIF_FILE"
          sarif html --output "./sarif_${BASENAME}.html" --no-autotrim "$SARIF_FILE"
          FOUND_FILES=1
        done < <(find "$SARIF_DIR" -maxdepth 1 -name "*.sarif" -type f -print0)

        if [ "$FOUND_FILES" -eq 0 ]; then
          echo "No .sarif files found in $SARIF_DIR"
          exit 1
        fi

    - name: Upload SARIF HTML reports
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.REPO_NAME }}-${{github.sha}}-sarif-html-reports
        path: sarif_*.html
        if-no-files-found: warn

    - name: Generate SBOM
      id: generate-sbom
      continue-on-error: true
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "Attempting to fetch SBOM from GitHub API..."
        TEMP_FILE="${REPO_NAME}-${{github.sha}}-sbom-temp.json"
        ERROR_OUTPUT=$(gh api /repos/${{ github.repository }}/dependency-graph/sbom 2>&1 > "$TEMP_FILE")
        EXIT_CODE=$?

        if [ $EXIT_CODE -ne 0 ]; then
          echo "::error::API call failed with exit code $EXIT_CODE"
          echo "::error::Error details: $ERROR_OUTPUT"
          echo "::warning::Failed to generate SBOM. The dependency graph may not be enabled for this repository."
          echo "::warning::Check: Repository Settings > Security > Dependency graph must be enabled"
          exit 1
        fi

        # Extract the SBOM from the API response (it's nested in a "sbom" key)
        jq '.sbom' "$TEMP_FILE" > "${REPO_NAME}-${{github.sha}}-sbom.spdx.json"
        rm "$TEMP_FILE"
        echo "SBOM generated successfully"

    - name: Upload SBOM
      if: steps.generate-sbom.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.REPO_NAME }}-${{github.sha}}-sbom
        path: ${{ env.REPO_NAME }}-${{github.sha}}-sbom.spdx.json
        if-no-files-found: warn

    - name: Attest Report with SBOM
      if: steps.generate-sbom.outcome == 'success'
      uses: actions/attest-sbom@v3
      with:
        subject-path: sarif_*.html, *.sarif
        sbom-path: ${{ env.REPO_NAME }}-${{github.sha}}-sbom.spdx.json

    - name: Attest
      if: steps.generate-sbom.outcome != 'success'
      uses: actions/attest-build-provenance@v3
      with:
        subject-path: sarif_*.html, *.sarif

    - name: Generate CodeQL Scan Summary
      shell: bash
      env:
        INPUT_SARIF_DIR: ${{ inputs.sarif-input }}
      run: |
        SARIF_DIR="$INPUT_SARIF_DIR"
        if [ -z "$SARIF_DIR" ]; then
          SARIF_DIR="${CODEQL_ACTION_SARIF_RESULTS_OUTPUT_DIR}"
        fi

        # Find SARIF files
        SARIF_FILES=($(find "$SARIF_DIR" -maxdepth 1 -name "*.sarif" -type f))
        SARIF_COUNT=${#SARIF_FILES[@]}

        if [ "$SARIF_COUNT" -eq 0 ]; then
          echo "No SARIF file found for summary generation"
          exit 0
        fi

        if [ "$SARIF_COUNT" -gt 1 ]; then
          echo "::warning::Multiple SARIF files found ($SARIF_COUNT). Summary generation for multiple files is not supported. Using the first file: ${SARIF_FILES[0]}"
        fi

        SARIF_FILE="${SARIF_FILES[0]}"

        # Extract information from SARIF file
        CODEQL_VERSION=$(jq -r '.runs[0].tool.driver.semanticVersion // "N/A"' "$SARIF_FILE")

        # Find build mode from toolExecutionNotifications
        BUILD_MODE=$(jq -r '
          .runs[0].invocations[0].toolExecutionNotifications[] |
          select(.descriptor.id == "cli/build-mode") |
          .properties.attributes.buildMode // "N/A"
        ' "$SARIF_FILE")

        # Count extracted files (count notifications with this ID pattern for any language)
        EXTRACTED_FILES=$(jq -r '
          [.runs[0].invocations[0].toolExecutionNotifications[] |
          select(.descriptor.id | contains("/diagnostics/successfully-extracted-files"))] | length
        ' "$SARIF_FILE")

        # Count detected files (count notifications with this ID pattern for any language)
        DETECTED_FILES=$(jq -r '
          [.runs[0].invocations[0].toolExecutionNotifications[] |
          select(.descriptor.id | startswith("cli/expected-extracted-files/"))] | length
        ' "$SARIF_FILE")

        # Get environment variables (with defaults if not set)
        ACTION_VERSION="${CODEQL_ACTION_VERSION:-N/A}"
        SCAN_STARTED="${CODEQL_WORKFLOW_STARTED_AT:-N/A}"
        ANALYSIS_KEY="${CODEQL_ACTION_ANALYSIS_KEY:-N/A}"

        # Generate markdown summary
        cat >> $GITHUB_STEP_SUMMARY << EOF
        # :shield: CodeQL Scan Summary

        ## Scan Information
        | Property | Value |
        |----------|-------|
        | **CodeQL Action Version** | \`${ACTION_VERSION}\` |
        | **Scan Started** | ${SCAN_STARTED} |
        | **Analysis Category** | \`${ANALYSIS_KEY}\` |

        ## CodeQL Engine Details
        | Property | Value |
        |----------|-------|
        | **CodeQL CLI Version** | \`${CODEQL_VERSION}\` |
        | **Build Mode** | \`${BUILD_MODE}\` |

        ## Analysis Metrics
        | Metric | Count |
        |--------|-------|
        | **Detected Files** | ${DETECTED_FILES} |
        | **Extracted Files** | ${EXTRACTED_FILES} |

        ---
        *Generated on $(date -u '+%Y-%m-%d %H:%M:%S UTC')*
        EOF

        echo "✅ CodeQL scan summary generated successfully"