name: 'CodeQL SARIF Report'
description: 'Generate and upload SARIF HTML reports from CodeQL analysis'
author: 'felickz'
branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  sarif-input:
    description: 'Path to the SARIF output directory. Defaults to CODEQL_ACTION_SARIF_RESULTS_OUTPUT_DIR environment variable set by codeql-action.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install sarif-tools
      shell: bash
      run: |
        pip install sarif-tools==2.0.0

    - name: Generate SARIF HTML reports
      shell: bash
      run: |
        SARIF_DIR="${{ inputs.sarif-input }}"
        if [ -z "$SARIF_DIR" ]; then
          SARIF_DIR="${CODEQL_ACTION_SARIF_RESULTS_OUTPUT_DIR}"
        fi
        
        if [ -z "$SARIF_DIR" ]; then
          echo "Error: No SARIF directory specified and CODEQL_ACTION_SARIF_RESULTS_OUTPUT_DIR is not set"
          exit 1
        fi
        
        if [ ! -d "$SARIF_DIR" ]; then
          echo "Error: SARIF directory not found: $SARIF_DIR"
          exit 1
        fi
        
        SARIF_FILES=$(find "$SARIF_DIR" -maxdepth 1 -name "*.sarif" -type f)
        if [ -z "$SARIF_FILES" ]; then
          echo "No .sarif files found in $SARIF_DIR"
          exit 1
        fi
        
        for SARIF_FILE in $SARIF_FILES; do
          BASENAME=$(basename "$SARIF_FILE" .sarif)
          echo "Generating HTML report for $SARIF_FILE"
          sarif html --output "./sarif_${BASENAME}.html" --no-autotrim "$SARIF_FILE"
        done

    - name: Upload SARIF HTML reports
      uses: actions/upload-artifact@v4
      with:
        name: sarif-html-reports
        path: sarif_*.html
        if-no-files-found: warn
